name: Go
on: [push, pull_request]

jobs:

  lint:    
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2      
      
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go get -v -t -d -u          
    - if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o MixerboxSync -v
    - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o MixerboxSync.exe -v
    - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o MixerboxSync -v
      
  test:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go get -v -t -d -u          
    - if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download    
    - run: go test -gcflags -l -v -coverprofile coverage.txt -covermode=atomic
    - uses: codecov/codecov-action@v1
