name: Go
on: [push, pull_request]

jobs:

  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go get -v -t -d -u          
    - if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - run: go build -v
    - run: go -gcflags=-l -v -cover
